<?php

include_once('annotate_ym.features.inc');

/**
 * @file
 *
 * We support links with nojs/* and ajax/*
 *
 * These links are supposed to have a class ctools-use-modal
 *
 * In this feature the view has added this class.
 */

/**
 * We add a menu handler for overlay nodes
 */
function annotate_ym_menu() {
  $items['nojs/node/%node/%'] = array(
    'page callback' => 'annotate_ym_ajax_node',
    'page arguments' => array(0, 2, 3),
    'access arguments' => array('post comments'),
  );
  $items['ajax/node/%node/%'] = array(
    'page callback' => 'annotate_ym_ajax_node',
    'page arguments' => array(0, 2, 3),
    'access arguments' => array('post comments'),
  );
  return $items;
}

function annotate_ym_init() {
  // Load the Ctools modal library and add the modal javascript.
  ctools_include('modal');
  ctools_modal_add_js();
}


function annotate_ym_ajax_node($js, $node, $command) {
  if (!ctools_js_load($js)) {
    drupal_goto(implode('/', array_shift(arg())));
  }

  // include node file, necessary for node generation
  module_load_include('inc', 'node', 'node.pages');

  if ($command == 'edit') {
    $config = array(
      'form_name' => $node->type . '_node_form',
    );
  }
  else if ($command == 'delete') {
    $config = array(
      'form_name' => 'node_delete_confirm',
    );
  }
  // TODO: view and others?
  else if ($command == 'view') {
    $config = array(
      'content' => node_view($node, TRUE, TRUE, FALSE),
    );
  }
  else {
    drupal_goto();
  }
  ctools_include('modal');
  ctools_include('ajax');

  if ($config['form_name']) {
    $form_state = array(
      'title' => t('Node'),
      'ajax' => TRUE,
    );
    $form_state['args'] = array($node);
    $output = ctools_modal_form_wrapper($config['form_name'], $form_state);
  }
  else {
    $output = array();
    $output[] = ctools_modal_command_display(t('Node'), $config['content']);
  }

  if (empty($output)) {
    $output = array();
    $output[] = ctools_modal_command_dismiss();
    //ctools_ajax_command_reload();
    //$output[] = ctools_modal_command_display('Thank you for you comment.', '<div class="modal-message">Your edit is saved.</div>');
    // empty $output signifies success, so we'll use it as our $commands array.
    //$inplace = ctools_ajax_text_button(t('remain here'), 'ctools_ajax_sample/nojs/login/inplace', t('Go to your account'));
    //$account = ctools_ajax_text_button(t('your account'), 'ctools_ajax_sample/nojs/login/user', t('Go to your account'));
    //$output[] = ctools_modal_command_display(t('Login Success'), '<div class="modal-message">Login successful. You can now choose whether to '. $inplace .', or go to '. $account.'.</div>');
  }
  ctools_ajax_render($output);
}
